auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Spincat.me
url:              http://spincat.me
feed:             /atom.xml
author:
    name:         Spincat
    weibo:        http://weibo.com/spincat
description:      "静若处子 动若疯猫"
author_info:      <a href="http://spincat.me/about">Spincat</a>

copyright: 2013 SpinCat.me

