auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            spincat.me
url:              http://spincat.me
feed:             /atom.xml
author:
    name:         spincat
    twitter:      twitter.com/spincat
description:      "spincat\'s Blog"
author_info:      <a href="http://spincat.me/about">spincat</a>

copyright:
    - Design by <a href="http://spincat.me/about" title="spincat" target="_blank">spincat</a> &copy; 2013
